### ISSUE TITLE
Comments more than issues

### ISSUE THREAD

**Issue by zapataf** [caseywdunn/phylogenetic_biology#10]
https://github.com/caseywdunn/phylogenetic_biology/blob/6547f834562cf53beaaf661b7aa96280a8852dbb/03-simulation.Rmd#L99

Two things:

* In the figure you don't have reversals to A after there has been a substitution to another nucleotide - is this on purpose?

* It's interesting you start this explanation in the context of DNA replication. When I talk about how this works, I explain it in the context of changes from the "ancestral" nucleotide site to the current site. "given that the ancestral sequence was A and today we see a C, through time it could have changed to A (no change), C, G, T, back to A, etc..." I mean, it's the same after all because DNA replication & inheritance from ancestor to descendant is the underlying process.

**Comment by caseywdunn** [comment]
Good catch - the intent of pane C in that figure wasn't clear. I was indicating that there are many possible histories of change that can explain specifically a change from A to C. I'll update the legend to make this clear.

Exactly. It is interesting to decide when to explain things in therms of process and when in terms of pattern. Here I wanted to make it clear that the model is an idealized hypothesis of process, so went with replication.
