### ISSUE TITLE
Another comment more than an issue

### ISSUE THREAD

**Issue by zapataf** [caseywdunn/phylogenetic_biology#11]
https://github.com/caseywdunn/phylogenetic_biology/blob/6547f834562cf53beaaf661b7aa96280a8852dbb/03-simulation.Rmd#L148

I love the way you explain this fundamental concept of phylogenetics, but this is precisely one concept that I often see as being completely misunderstood by students and even by phylogeneticists. Not sure if adding some adjectives or something to highlight the critical importance of this central "problem" of phylogenetics (and how, as you mention at the end, dating with fossils or tip dating with viruses help disentangle time-rate)

**Comment by caseywdunn** [comment]
Glad you think it was worth addressing this - I debated whether it was worth the space so this is really helpful feedback.
