### ISSUE TITLE
Chapter 6 miscellany

### ISSUE THREAD

**Issue by beroe** [caseywdunn/phylogenetic_biology#30]
Comments on chapter 6:
* Haven't read ahead yet, but will you talk about amino acid models? (Maybe just mention there are comparable sets of models for AAs?)
* `The GTR model 11 parameters.`  Missing the verb.
* `so that they can differ from each other. ` You go straight into how a-f have to add to 6, but a simple example like you do for π (Just something simple like 0.5 means equal probability of transition from X to Y  while 0.2 means ...) would really help explain 
* `In typical use,  mu=1`  Should that be `µ`?
* `That means that the best possible likelihood under HKY85 is also available under GTR` -- good message.
* `there are challenges far short of this extreme example`  - little bit awkward?
* When talking about `I` and `G` maybe use the Γ symbol and put (gamma) in parentheses? G is usually a lazy shortcut for finding the gamma key, right?
* `the topology we are evaluating is the focal topology` -- should be `as the` -- and maybe *bold* focal topology.
* `focal tree as a whole be asking how frequent` -- by asking
* `It jsut indicates how frequently an edge is recovered `--> `just`

**Comment by caseywdunn** [comment]
Will get to amino acids later. Decided to focus entirely on DNA while putting all the pieces together, then circle back and add other approaches in.
